# Generated by Django 3.2 on 2021-05-11 17:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('gender', django_mysql.models.EnumField(choices=[('M', 'M'), ('F', 'F'), ('non-binary', 'non-binary'), ('rather not say', 'rather not say')], default='rather not say')),
                ('phno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('gender', django_mysql.models.EnumField(choices=[('M', 'M'), ('F', 'F'), ('non-binary', 'non-binary'), ('rather not say', 'rather not say')], default='rather not say')),
                ('phno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('dept', django_mysql.models.EnumField(choices=[('IT', 'IT'), ('BT', 'BT'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')])),
                ('semester', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
    ]
