# Generated by Django 3.2 on 2021-04-18 09:05

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subcode', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('dept', django_mysql.models.EnumField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('BT', 'BT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('AERO', 'AERO'), ('CHEM', 'CHEM')])),
            ],
            options={
                'db_table': 'subjects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='syllabusfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', django_mysql.models.EnumField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('key', models.CharField(max_length=200)),
                ('subcode', models.ForeignKey(blank=True, db_column='subcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.subjects')),
            ],
            options={
                'db_table': 'syllabusfeed',
                'managed': True,
            },
        ),
    ]
