# Generated by Django 3.2 on 2021-05-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='sem',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='enrolledsub',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sub1', models.ForeignKey(blank=True, db_column='subcode1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcode1', to='dashboard.subjects')),
                ('sub2', models.ForeignKey(blank=True, db_column='subcode2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcode2', to='dashboard.subjects')),
                ('sub3', models.ForeignKey(blank=True, db_column='subcode3', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcode3', to='dashboard.subjects')),
                ('sub4', models.ForeignKey(blank=True, db_column='subcode4', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcode4', to='dashboard.subjects')),
                ('sub5', models.ForeignKey(blank=True, db_column='subcode5', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcode5', to='dashboard.subjects')),
                ('sub6', models.ForeignKey(blank=True, db_column='subcode6', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcode6', to='dashboard.subjects')),
            ],
            options={
                'db_table': 'enrolledsub',
                'managed': True,
            },
        ),
    ]
