# Generated by Django 3.2 on 2021-05-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_syllabusfeed_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabusfeed',
            name='key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='syllabusfeed',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
